/**
 * Dữ liệu mẫu cho seeding (tài khoản, phim, suất chiếu, ...).
 * Mật khẩu dạng plain text — seedService sẽ bcrypt trước khi ghi DB.
 */

export const seedData = {
  users: [
    {
      username: 'admin',
      password: 'admin123',
      email: 'admin@pele.local',
      fullName: 'Quản trị PELE',
      phone: '0900000001',
      role: 'ADMIN',
      wallet: 500000,
      age: 28,
    },
    {
      username: 'user1',
      password: 'user123',
      email: 'user1@pele.local',
      fullName: 'Nguyễn Văn A',
      phone: '0900000002',
      role: 'USER',
      wallet: 120000,
      age: 22,
    },
    {
      username: 'user2',
      password: 'user123',
      email: 'user2@pele.local',
      fullName: 'Trần Thị B',
      phone: '0900000003',
      role: 'USER',
      wallet: 90000,
      age: 24,
    },
    {
      username: 'demo',
      password: 'demo123',
      email: 'demo@pele.local',
      fullName: 'Tài khoản Demo',
      phone: '0900000004',
      role: 'USER',
      wallet: 0,
      age: 18,
    },
  ],

  rooms: [
    { id: 1, name: 'Phòng 01', totalRows: 10, totalCols: 10 },
    { id: 2, name: 'Phòng 02', totalRows: 10, totalCols: 10 },
    { id: 3, name: 'Phòng IMAX (demo)', totalRows: 10, totalCols: 12 },
  ],

  movies: [
    {
      id: 1,
      title: 'Mai',
      description: 'Phim Việt — dữ liệu demo PELE Cinema.',
      director: 'Trấn Thành',
      cast: 'Phương Anh Đào, Tuấn Trần',
      duration: 120,
      releaseDate: '2025-01-15',
      posterUrl: 'https://picsum.photos/seed/mai/400/600',
      genre: 'Tình cảm',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      id: 2,
      title: 'Đào, Phở và Piano',
      description: 'Phim Việt — demo.',
      director: 'Phi Tiến Sơn',
      cast: 'Tùng, Bảo Anh',
      duration: 110,
      releaseDate: '2025-02-01',
      posterUrl: 'https://picsum.photos/seed/daopho/400/600',
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      id: 3,
      title: 'Avatar: Fire and Ash (demo)',
      description: 'Phim sắp chiếu — demo.',
      director: 'James Cameron',
      cast: 'Sam Worthington, Zoe Saldaña',
      duration: 180,
      releaseDate: null,
      posterUrl: 'https://picsum.photos/seed/avatar/400/600',
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      id: 4,
      title: 'Dune: Part Three (demo)',
      description: 'Khoa học viễn tưởng — demo.',
      director: 'Denis Villeneuve',
      cast: 'Timothée Chalamet',
      duration: 165,
      releaseDate: '2026-06-01',
      posterUrl: 'https://picsum.photos/seed/dune/400/600',
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      id: 5,
      title: 'Nụ hôn bạc triệu (demo)',
      description: 'Hài lãng mạn — demo.',
      director: 'Đạo diễn X',
      cast: 'Dàn diễn viên Y',
      duration: 105,
      releaseDate: '2025-08-20',
      posterUrl: 'https://picsum.photos/seed/comedy/400/600',
      genre: 'Hài',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      id: 6,
      title: 'Kẻ săn đêm (demo)',
      description: 'Hành động — demo.',
      director: 'Đạo diễn Z',
      cast: 'Diễn viên Z',
      duration: 128,
      releaseDate: '2025-11-10',
      posterUrl: 'https://picsum.photos/seed/action/400/600',
      genre: 'Hành động',
      trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
  ],

  showtimes: [
    { id: 1, movieId: 1, roomId: 1, offsetDays: 1, hour: 19, minute: 30, price: 80000 },
    { id: 2, movieId: 2, roomId: 2, offsetDays: 2, hour: 20, minute: 0, price: 90000 },
    { id: 3, movieId: 1, roomId: 1, offsetDays: 3, hour: 14, minute: 0, price: 75000 },
    { id: 4, movieId: 4, roomId: 3, offsetDays: 5, hour: 21, minute: 15, price: 120000 },
    { id: 5, movieId: 5, roomId: 2, offsetDays: 7, hour: 18, minute: 45, price: 85000 },
  ],

  products: [
    { id: 1, name: 'Combo Bắp + 2 Nước', category: 'Combo', price: 99000, imageUrl: null, active: true },
    { id: 2, name: 'Pepsi', category: 'Nước', price: 25000, imageUrl: null, active: true },
    { id: 3, name: 'Nước suối', category: 'Nước', price: 15000, imageUrl: null, active: true },
  ],

  promotions: [
    {
      id: 1,
      code: 'PELE10',
      title: 'Giảm 10%',
      description: 'Áp dụng toàn hệ thống (demo).',
      discountAmount: 0,
      discountPercent: 10,
      expiresOffsetDays: 30,
      active: true,
      showtimeId: null,
    },
    {
      id: 2,
      code: 'GIAM50K',
      title: 'Giảm 50.000đ',
      description: 'Mã giảm tiền demo.',
      discountAmount: 50000,
      discountPercent: 0,
      expiresOffsetDays: 30,
      active: true,
      showtimeId: null,
    },
  ],

  news: [
    {
      id: 1,
      title: 'PELE Cinema khai trương ưu đãi',
      content: 'Nội dung demo: rạp mở cửa với nhiều suất chiếu và combo bắp nước hấp dẫn.',
      excerpt: 'Ưu đãi khai trương tuần này.',
      imageUrl: null,
      category: 'Sự kiện',
      author: 'PELE News',
      active: true,
    },
    {
      id: 2,
      title: 'Top phim tuần này',
      content: 'Danh sách phim đang hot tại PELE Cinema.',
      excerpt: 'Xem gợi ý phim hay.',
      imageUrl: null,
      category: 'Gợi ý',
      author: 'PELE News',
      active: true,
    },
    {
      id: 3,
      title: 'Gợi ý combo bắp nước',
      content: 'Đặt combo online để nhận thêm ưu đãi.',
      excerpt: 'Combo tiết kiệm.',
      imageUrl: null,
      category: 'Khuyến mãi',
      author: 'PELE News',
      active: true,
    },
  ],
}

